{
    'name': 'MYIS Payslip Email Sender',
    'version': '18.0.1.0.0',
    'summary': 'Send payslip emails to employees',
    'description': 'Send payslip emails to employees with tracking',
    'author': 'MYIS IT Department',
    'website': 'https://myis.ac.th',
    'category': 'Human Resources',
    'depends': ['hr', 'mail'],
    'data': [],
    'installable': True,
    'auto_install': False,
    'application': False,
    'license': 'LGPL-3',
}
